### ISSUE TITLE
Dockerで環境構築する

### ISSUE THREAD

**Issue by Suntory-Y-Water** [Suntory-Y-Water/next.js-micro-blog#7]
## 対象範囲

フロントエンドは1個でOK
バックエンドはJava、JavaScript、Pythonそれぞれのコンテナを作成し起動させる。

**Comment by Suntory-Y-Water** [comment]
以前使ったイメージを使い回してみる

``` Dockerfile

# ベースイメージ
FROM node:20.9.0

# 作業ディレクトリの設定
WORKDIR /app

# 依存関係のインストール
COPY package.json package-lock.json ./
RUN npm install

# ポートの公開
EXPOSE 3000

# 実行コマンド
CMD ["npm", "run", "dev"]

```

**Comment by Suntory-Y-Water** [comment]
起動したらJsonサーバーの生き残りがいて思いっきりエラーになった。
Javaのパスにとんでも500番えらーになったので改善したい

**Comment by Suntory-Y-Water** [comment]
## ホットリロードできない問題

1. ボリュームマウント設定をオンにするため、名前つきで`node_modules`を設定する。
2. `next.config.js`に以下の内容を追加する。

``` js
/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: ['source.unsplash.com'],
  },
  // このへん
  reactStrictMode: true,
  swcMinify: true,
  webpack: (config, context) => {
    config.watchOptions = {
      poll: 1000,
      aggregateTimeout: 300,
    };
    return config;
  },
  // このへん
};

module.exports = nextConfig;
```

参考になりそうなもの
[[Docker環境構築におけるnextjsのホットリロード不可問題 - Qiita](https://qiita.com/fur_orannge/items/90339eab0cd9142dc830)](https://qiita.com/fur_orannge/items/90339eab0cd9142dc830)

https://github.com/vercel/next.js/issues/36774

**Comment by Suntory-Y-Water** [comment]
json-serverはシンプルにcompose.yamlに設定を追加すればOK

``` yaml
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" 
      - "3001:3001" # 追加
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
    command: sh -c "npm run json & npm run dev" # 追加
```
